; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:crowpanel5]
platform = espressif32@6.13.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
upload_speed = 921600
lib_deps = 
	lvgl/lvgl@~8.3.11
	lovyan03/LovyanGFX@1.1.16
	bblanchon/ArduinoJson@~7.3.0
build_flags = 
	-Iinclude
	-DBOARD_HAS_PSRAM
	-DCONFIG_SPIRAM_SUPPORT=1
	-DLV_CONF_INCLUDE_SIMPLE
	-DLV_CONF_SUPPRESS_DEFINE_CHECK
	-DSCREEN_WIDTH=800
	-DSCREEN_HEIGHT=480
	-DLOG_LEVEL=LOG_LEVEL_INFO
	-O2
	-Wno-missing-field-initializers
build_type = debug
monitor_filters = esp32_exception_decoder

[env:crowpanel7]
platform = https://github.com/pioarduino/platform-espressif32.git#develop
board = esp32-p4
framework = espidf
monitor_speed = 115200
upload_port = COM4
board_build.flash_mode = qio
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
board_build.cmake_extra_args =
	-DSDKCONFIG_DEFAULTS=sdkconfig.defaults.crowpanel7
build_flags =
	-DCROWPANEL_P4=1
	-DSCREEN_WIDTH=1024
	-DSCREEN_HEIGHT=600
build_type = debug
monitor_filters = esp32_exception_decoder
